### PR TITLE
Add note about the binary-id flag to the readme

### PR DESCRIPTION
**Pull request by pdgonzalez872**
as discussed here: https://github.com/aaronrenner/phx_gen_auth/issues/57

### CODE REVIEW

**Comment by pdgonzalez872** [comment]
@aaronrenner maybe this got buried? If you don't want to merge it in, no worries! Just touching base on this. Thanks!

**Comment by aaronrenner** [comment]
@pdgonzalez872 Thanks for the PR. Since phx_gen_auth automatically uses binary ids if the original phoenix app was generated with binary ids, I’m not sure that this needs to be called out as prominently in the README. However, I have been leaving it open to remind me to see if I can add some more info to the docs about it. I appreciate you sharing that this was confusing and I’ll keep thinking about making this info easier to discover.

**Comment by pdgonzalez872** [comment]
Oh interesting, that was not my use case at first. I created a phx app, then said: cool, let's use the auth generator. No thoughts further than that at that time.

Interesting about not wanting to add to the readme. I guess I see it as a great feature that I'd want to be loud about up front, not something I'd want to add as a side note a couple of clicks away. Just my opinion though :) Maybe this would belong in a `guide` instead?

Feel free to keep it open and I won't be sad if you don't end up using it. Just thought you'd want some UX experience.

Thanks for the generator! :heart: !!

**Comment by wulymammoth** [comment]
@pdgonzalez872 I think you make a fair point, but to keep the documentation for gen-auth concise, I think it makes sense to move it to a guide or FAQ when/if there is one. It would be worth mentioning in the Phoenix Guides in my opinion

I think gen-auth following whatever has already been established in a Phoenix app makes sense. It would be worth calling out if, by default, gen-auth used something different IMO

Seeing how many questions come up related to various aspects of gen-auth, I think an FAQ somewhere would help, because the questions range from general questions about how to do authentication, to authentication patterns, and all the way to the naming scheme used, so what I'm thinking it should cover at minimum are:
1. understanding authentication and the various protocols -- link to some resource, because I think the primary consumer for gen-auth has a general understanding of authentication
2. what gen-auth is
3. what gen-auth is NOT

**Comment by aaronrenner** [comment]
@pdgonzalez872 Thanks for submitting a PR for this. 

I ended up adding the note to the Readme like you suggested, but reworked the wording a bit.

**Comment by pdgonzalez872** [comment]
Cool! Thank YOU for the generator!

**Pull request closed without merging**
