### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dbi1**
Added a small note about installing 'make'. 

Not an issue for experienced devs, but saves less experienced developers an error when running the migration.

Thanks!

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you!

We need `make` to compile the dependencies but, if `make` is not available, I would say it is the responsibility of the `elixir_make` project to raise a good error message instead. WDYT?

**Comment by dbi1** [comment]
That sounds good, especially if the formatting and wording of the message are helpful and keep the user on the "fast track to success" :) Very satisfying when one gets something up and running right away...

I really like the way Phoenix ends its new app install process with a well-formatted list of things still to be done that are easy to understand and follow ("We are almost there! The following steps are missing...")

Re `elixir_make`, I'm assuming that would mean adding install instructions for it to this readme here?

**Comment by josevalim** [comment]
> Re elixir_make, I'm assuming that would mean adding install instructions for it to this readme here?

Not really because I don't think people will read that README. However, I think elixir_make is the best tool to tell people what to do when it is missing. For example, BSD-based systems and Windows won't install `make` but either `nmake` or `gmake`, so the suggestion in this PR would be innacurate. So it is best if `elixir_make` errors if it is not available with the most accurate instructions.

**Comment by dbi1** [comment]
Got it, sounds good!

**Pull request closed without merging**
